import { createContext, ReactNode, useContext, useEffect, useState } from "react";

export type Theme = "light" | "dark" | "system";
export type Language = "en" | "it" | "es" | "fr" | "de" | "zh" | "ja" | "pt" | "ru";

// Oggetto che contiene le traduzioni per ogni lingua
export const translations = {
  en: {
    settings: "Settings",
    settingsDescription: "Customize your experience by changing theme and language",
    theme: "Theme",
    language: "Language",
    system: "System",
    light: "Light",
    dark: "Dark",
    favorites: "Favorites",
    noFavorites: "No favorites added",
    addToFavorites: "Add to favorites",
    removeFromFavorites: "Remove from favorites",
    english: "English",
    italian: "Italian",
    spanish: "Spanish",
    french: "French",
    german: "German",
    chinese: "Chinese",
    japanese: "Japanese",
    portuguese: "Portuguese",
    russian: "Russian",
    close: "Close",
    login: "Login",
    logout: "Logout",
    admin: "Admin",
    search: "Search services...",
    serverStatus: "SERVER STATUS",
    selectTheme: "Select theme",
    selectLanguage: "Select language",
    operational: "Operational",
    degraded: "Degraded performance",
    down: "Down",
    lastUpdated: "Last updated",
    dashboard: "Dashboard",
    dashboardDescription: "Check the status of services in real time and get instant updates.",
    checkingNow: "Checking...",
    checkNow: "Check Now",
    accountTitle: "Your Account",
    username: "Username",
    email: "Email",
    role: "Role",
    registeredAt: "Registered on",
    backToDashboard: "Back to Dashboard",
    loggingOut: "Logging out...",
    heroDescription: "Monitor the operational status of various services and platforms in real time. Stay informed about outages and performance issues.",
    loginDescription: "Enter your credentials to log in",
    registerDescription: "Create a new account to access the dashboard",
    emailPlaceholder: "Enter your email",
    passwordPlaceholder: "Enter your password",
    usernamePlaceholder: "Choose a username",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your password",
    passwordMismatch: "Passwords do not match",
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    to: "to",
    toPresent: "to present",
    unknown: "Unknown",
    currentStatus: "Current Status",
    responseTime: "Response Time",
    uptime30d: "Uptime (30 days)",
    lastOutage: "Last Outage",
    avgResponse: "Avg. Response",
    uptimeHistory: "Uptime History",
    recentIncidents: "Recent Incidents",
    noHistoryAvailable: "No history available",
    noIncidentsReported: "No incidents reported",
    noRecentOutages: "No recent outages",
    overall: "Overall Status",
    partialOutage: "Partial Outage",
    categories: "Categories",
    lastCheck: "Last check",
    games: "Games",
    streaming: "Streaming",
    bank: "Bank",
    social: "Social",
    mail: "Mail",
    shopping: "Shopping",
    various: "Various",
    connection: "Connection",
    browserai: "Browser & AI",
    infoAndContacts: "Info & Contacts",
    expand: "Expand",
    collapse: "Collapse",
    searchServices: "Search services"
  },
  it: {
    settings: "Impostazioni",
    settingsDescription: "Personalizza la tua esperienza cambiando tema e lingua",
    theme: "Tema",
    language: "Lingua",
    system: "Sistema",
    light: "Chiaro",
    dark: "Scuro",
    favorites: "Preferiti",
    noFavorites: "Nessun preferito aggiunto",
    addToFavorites: "Aggiungi ai preferiti",
    removeFromFavorites: "Rimuovi dai preferiti",
    english: "Inglese",
    italian: "Italiano",
    spanish: "Spagnolo",
    french: "Francese",
    german: "Tedesco",
    chinese: "Cinese",
    japanese: "Giapponese",
    portuguese: "Portoghese",
    russian: "Russo",
    close: "Chiudi",
    login: "Accedi",
    logout: "Esci",
    admin: "Amministratore",
    search: "Cerca servizi...",
    serverStatus: "STATO DEI SERVER",
    selectTheme: "Seleziona tema",
    selectLanguage: "Seleziona lingua",
    operational: "Operativo",
    degraded: "Prestazioni degradate",
    down: "Non disponibile",
    lastUpdated: "Ultimo aggiornamento",
    dashboard: "Dashboard",
    dashboardDescription: "Controlla lo stato dei servizi in tempo reale e ricevi aggiornamenti immediati.",
    checkingNow: "Controllo in corso...",
    checkNow: "Controlla ora",
    accountTitle: "Il tuo Account",
    username: "Username",
    email: "Email",
    role: "Ruolo",
    registeredAt: "Registrato il",
    backToDashboard: "Torna alla Dashboard",
    loggingOut: "Logout...",
    heroDescription: "Monitora lo stato operativo dei vari servizi e piattaforme in tempo reale. Rimani informato su interruzioni e problemi di prestazione.",
    loginDescription: "Inserisci le tue credenziali per accedere all'account",
    registerDescription: "Crea un nuovo account per accedere alla dashboard",
    emailPlaceholder: "Inserisci la tua email",
    passwordPlaceholder: "Inserisci la tua password",
    usernamePlaceholder: "Scegli un username",
    confirmPassword: "Conferma Password",
    confirmPasswordPlaceholder: "Conferma la tua password",
    passwordMismatch: "Le password non corrispondono",
    loggingIn: "Accesso in corso...",
    creatingAccount: "Creazione account in corso...",
    to: "alle",
    toPresent: "ad ora",
    unknown: "Sconosciuto",
    currentStatus: "Stato Attuale",
    responseTime: "Tempo di Risposta",
    uptime30d: "Uptime (30 giorni)",
    lastOutage: "Ultima Interruzione",
    avgResponse: "Risposta Media",
    uptimeHistory: "Storico Uptime",
    recentIncidents: "Incidenti Recenti",
    noHistoryAvailable: "Nessuno storico disponibile",
    noIncidentsReported: "Nessun incidente segnalato",
    noRecentOutages: "Nessuna interruzione recente",
    overall: "Stato Generale",
    partialOutage: "Interruzione Parziale",
    categories: "Categorie",
    lastCheck: "Ultimo controllo",
    games: "Giochi",
    streaming: "Streaming",
    bank: "Banche",
    social: "Social",
    mail: "Mail",
    shopping: "Shopping",
    various: "Varie",
    connection: "Connessione",
    browserai: "Browser & IA",
    infoAndContacts: "Info & Contatti",
    expand: "Espandi",
    collapse: "Comprimi",
    searchServices: "Cerca servizi"
  },
  es: {
    settings: "Configuración",
    settingsDescription: "Personaliza tu experiencia cambiando el tema y el idioma",
    theme: "Tema",
    language: "Idioma",
    system: "Sistema",
    light: "Claro",
    dark: "Oscuro",
    favorites: "Favoritos",
    noFavorites: "No hay favoritos añadidos",
    addToFavorites: "Añadir a favoritos",
    removeFromFavorites: "Eliminar de favoritos",
    english: "Inglés",
    italian: "Italiano",
    spanish: "Español",
    french: "Francés",
    german: "Alemán",
    chinese: "Chino",
    japanese: "Japonés",
    portuguese: "Portugués",
    russian: "Ruso",
    close: "Cerrar",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    admin: "Administrador",
    search: "Buscar servicios...",
    serverStatus: "ESTADO DEL SERVIDOR",
    selectTheme: "Seleccionar tema",
    selectLanguage: "Seleccionar idioma",
    operational: "Operativo",
    degraded: "Rendimiento degradado",
    down: "Inactivo",
    lastUpdated: "Última actualización",
    accountTitle: "Tu Cuenta",
    username: "Usuario",
    email: "Correo electrónico",
    role: "Rol",
    registeredAt: "Registrado el",
    backToDashboard: "Volver al Panel",
    loggingOut: "Cerrando sesión...",
    heroDescription: "Monitorea el estado operativo de varios servicios y plataformas en tiempo real. Mantente informado sobre interrupciones y problemas de rendimiento.",
    loginDescription: "Introduce tus credenciales para iniciar sesión",
    registerDescription: "Crea una nueva cuenta para acceder al panel",
    emailPlaceholder: "Introduce tu correo electrónico",
    passwordPlaceholder: "Introduce tu contraseña",
    usernamePlaceholder: "Elige un nombre de usuario",
    confirmPassword: "Confirmar Contraseña",
    confirmPasswordPlaceholder: "Confirma tu contraseña",
    passwordMismatch: "Las contraseñas no coinciden",
    loggingIn: "Iniciando sesión...",
    creatingAccount: "Creando cuenta...",
    to: "hasta",
    toPresent: "hasta ahora",
    unknown: "Desconocido",
    currentStatus: "Estado Actual",
    responseTime: "Tiempo de Respuesta",
    uptime30d: "Tiempo Activo (30 días)",
    lastOutage: "Última Interrupción",
    avgResponse: "Respuesta Media",
    uptimeHistory: "Historial de Actividad",
    recentIncidents: "Incidentes Recientes",
    noHistoryAvailable: "No hay historial disponible",
    noIncidentsReported: "No hay incidentes reportados",
    noRecentOutages: "Sin interrupciones recientes",
    overall: "Estado General",
    partialOutage: "Interrupción Parcial",
    categories: "Categorías",
    lastCheck: "Última comprobación",
    games: "Juegos",
    streaming: "Streaming",
    bank: "Banco",
    social: "Social",
    mail: "Correo",
    shopping: "Compras",
    various: "Varios",
    connection: "Conexión",
    browserai: "Navegador & IA",
    infoAndContacts: "Info & Contactos",
    expand: "Expandir",
    collapse: "Contraer",
    searchServices: "Buscar servicios"
  },
  fr: {
    settings: "Paramètres",
    settingsDescription: "Personnalisez votre expérience en changeant de thème et de langue",
    theme: "Thème",
    language: "Langue",
    system: "Système",
    light: "Clair",
    dark: "Sombre",
    favorites: "Favoris",
    noFavorites: "Aucun favori ajouté",
    addToFavorites: "Ajouter aux favoris",
    removeFromFavorites: "Retirer des favoris",
    english: "Anglais",
    italian: "Italien",
    spanish: "Espagnol",
    french: "Français",
    german: "Allemand",
    chinese: "Chinois",
    japanese: "Japonais",
    portuguese: "Portugais",
    russian: "Russe",
    close: "Fermer",
    login: "Connexion",
    logout: "Déconnexion",
    admin: "Admin",
    search: "Rechercher des services...",
    serverStatus: "ÉTAT DU SERVEUR",
    selectTheme: "Sélectionner un thème",
    selectLanguage: "Sélectionner une langue",
    operational: "Opérationnel",
    degraded: "Performances dégradées",
    down: "Indisponible",
    lastUpdated: "Dernière mise à jour",
    accountTitle: "Votre Compte",
    username: "Nom d'utilisateur",
    email: "E-mail",
    role: "Rôle",
    registeredAt: "Enregistré le",
    backToDashboard: "Retour au tableau de bord",
    loggingOut: "Déconnexion...",
    heroDescription: "Surveillez l'état opérationnel de divers services et plateformes en temps réel. Restez informé des pannes et des problèmes de performance.",
    loginDescription: "Entrez vos identifiants pour vous connecter",
    registerDescription: "Créez un nouveau compte pour accéder au tableau de bord",
    emailPlaceholder: "Entrez votre e-mail",
    passwordPlaceholder: "Entrez votre mot de passe",
    usernamePlaceholder: "Choisissez un nom d'utilisateur",
    confirmPassword: "Confirmer le mot de passe",
    confirmPasswordPlaceholder: "Confirmez votre mot de passe",
    passwordMismatch: "Les mots de passe ne correspondent pas",
    loggingIn: "Connexion...",
    creatingAccount: "Création du compte...",
    to: "à",
    toPresent: "à présent",
    unknown: "Inconnu",
    currentStatus: "État Actuel",
    responseTime: "Temps de Réponse",
    uptime30d: "Disponibilité (30 jours)",
    lastOutage: "Dernière Panne",
    avgResponse: "Réponse Moyenne",
    uptimeHistory: "Historique de Disponibilité",
    recentIncidents: "Incidents Récents",
    noHistoryAvailable: "Aucun historique disponible",
    noIncidentsReported: "Aucun incident signalé",
    noRecentOutages: "Aucune panne récente",
    overall: "État Général",
    partialOutage: "Panne Partielle",
    categories: "Catégories",
    lastCheck: "Dernier contrôle",
    games: "Jeux",
    streaming: "Streaming",
    bank: "Banque",
    social: "Social",
    mail: "Mail",
    shopping: "Shopping",
    various: "Divers",
    connection: "Connexion",
    browserai: "Navigateur & IA",
    infoAndContacts: "Infos & Contacts",
    expand: "Développer",
    collapse: "Réduire",
    searchServices: "Rechercher des services"
  },
  de: {
    settings: "Einstellungen",
    theme: "Thema",
    language: "Sprache",
    system: "System",
    light: "Hell",
    dark: "Dunkel",
    favorites: "Favoriten",
    noFavorites: "Keine Favoriten hinzugefügt",
    addToFavorites: "Zu Favoriten hinzufügen",
    removeFromFavorites: "Aus Favoriten entfernen",
    english: "Englisch",
    italian: "Italienisch",
    spanish: "Spanisch",
    french: "Französisch",
    german: "Deutsch",
    chinese: "Chinesisch",
    japanese: "Japanisch",
    portuguese: "Portugiesisch",
    russian: "Russisch",
    close: "Schließen",
    login: "Anmelden",
    logout: "Abmelden",
    admin: "Administrator",
    search: "Dienste suchen...",
    serverStatus: "SERVER-STATUS",
    accountTitle: "Dein Konto",
    username: "Benutzername",
    email: "E-Mail",
    role: "Rolle",
    registeredAt: "Registriert am",
    backToDashboard: "Zurück zum Dashboard",
    loggingOut: "Abmelden...",
    heroDescription: "Überwache den Betriebsstatus verschiedener Dienste und Plattformen in Echtzeit. Bleibe über Ausfälle und Leistungsprobleme informiert.",
    loginDescription: "Gib deine Zugangsdaten ein, um dich anzumelden",
    registerDescription: "Erstelle ein neues Konto, um auf das Dashboard zuzugreifen",
    emailPlaceholder: "Gib deine E-Mail ein",
    passwordPlaceholder: "Gib dein Passwort ein",
    usernamePlaceholder: "Wähle einen Benutzernamen",
    confirmPassword: "Passwort bestätigen",
    confirmPasswordPlaceholder: "Bestätige dein Passwort",
    passwordMismatch: "Passwörter stimmen nicht überein",
    loggingIn: "Anmeldung...",
    creatingAccount: "Konto wird erstellt...",
    to: "bis",
    toPresent: "bis jetzt",
    unknown: "Unbekannt",
    categories: "Kategorien",
    lastCheck: "Letzte Prüfung",
    games: "Spiele",
    streaming: "Streaming",
    bank: "Bank",
    social: "Soziales",
    mail: "Mail",
    shopping: "Einkaufen",
    various: "Verschiedenes",
    connection: "Verbindung",
    browserai: "Browser & KI",
    infoAndContacts: "Info & Kontakte",
    expand: "Erweitern",
    collapse: "Einklappen",
    searchServices: "Dienste suchen"
  },
  zh: {
    settings: "设置",
    theme: "主题",
    language: "语言",
    system: "系统",
    light: "明亮",
    dark: "暗黑",
    favorites: "收藏夹",
    noFavorites: "未添加收藏",
    addToFavorites: "添加到收藏夹",
    removeFromFavorites: "从收藏夹中移除",
    english: "英语",
    italian: "意大利语",
    spanish: "西班牙语",
    french: "法语",
    german: "德语",
    chinese: "中文",
    japanese: "日语",
    portuguese: "葡萄牙语",
    russian: "俄语",
    close: "关闭",
    login: "登录",
    logout: "登出",
    admin: "管理员",
    search: "搜索服务...",
    serverStatus: "服务器状态",
    accountTitle: "你的账户",
    username: "用户名",
    email: "电子邮件",
    role: "角色",
    registeredAt: "注册于",
    backToDashboard: "返回仪表板",
    loggingOut: "正在登出...",
    heroDescription: "实时监控各种服务和平台的运行状态。随时了解中断和性能问题。",
    loginDescription: "输入您的凭据登录",
    registerDescription: "创建新账户以访问仪表板",
    emailPlaceholder: "输入您的电子邮件",
    passwordPlaceholder: "输入您的密码",
    usernamePlaceholder: "选择用户名",
    confirmPassword: "确认密码",
    confirmPasswordPlaceholder: "确认您的密码",
    passwordMismatch: "密码不匹配",
    loggingIn: "正在登录...",
    creatingAccount: "正在创建账户...",
    to: "至",
    toPresent: "至今",
    unknown: "未知",
    categories: "类别",
    lastCheck: "上次检查",
    games: "游戏",
    streaming: "流媒体",
    bank: "银行",
    social: "社交",
    mail: "邮件",
    shopping: "购物",
    various: "其他",
    connection: "连接",
    browserai: "浏览器与AI",
    infoAndContacts: "信息和联系方式",
    expand: "展开",
    collapse: "收起",
    searchServices: "搜索服务"
  },
  ja: {
    settings: "設定",
    theme: "テーマ",
    language: "言語",
    system: "システム",
    light: "ライト",
    dark: "ダーク",
    favorites: "お気に入り",
    noFavorites: "お気に入りがありません",
    addToFavorites: "お気に入りに追加",
    removeFromFavorites: "お気に入りから削除",
    english: "英語",
    italian: "イタリア語",
    spanish: "スペイン語",
    french: "フランス語",
    german: "ドイツ語",
    chinese: "中国語",
    japanese: "日本語",
    portuguese: "ポルトガル語",
    russian: "ロシア語",
    close: "閉じる",
    login: "ログイン",
    logout: "ログアウト",
    admin: "管理者",
    search: "サービスを検索...",
    serverStatus: "サーバーステータス",
    accountTitle: "あなたのアカウント",
    username: "ユーザー名",
    email: "メールアドレス",
    role: "役割",
    registeredAt: "登録日",
    backToDashboard: "ダッシュボードに戻る",
    loggingOut: "ログアウト中...",
    heroDescription: "さまざまなサービスやプラットフォームの稼働状況をリアルタイムで監視します。障害やパフォーマンス問題を常に把握しましょう。",
    loginDescription: "ログインするには認証情報を入力してください",
    registerDescription: "ダッシュボードにアクセスするために新しいアカウントを作成してください",
    emailPlaceholder: "メールアドレスを入力してください",
    passwordPlaceholder: "パスワードを入力してください",
    usernamePlaceholder: "ユーザー名を選択してください",
    confirmPassword: "パスワードの確認",
    confirmPasswordPlaceholder: "パスワードを確認してください",
    passwordMismatch: "パスワードが一致しません",
    loggingIn: "ログイン中...",
    creatingAccount: "アカウント作成中...",
    to: "まで",
    toPresent: "現在まで",
    unknown: "不明",
    categories: "カテゴリー",
    lastCheck: "最終チェック",
    games: "ゲーム",
    streaming: "ストリーミング",
    bank: "銀行",
    social: "ソーシャル",
    mail: "メール",
    shopping: "ショッピング",
    various: "その他",
    connection: "接続",
    browserai: "ブラウザ＆AI",
    infoAndContacts: "情報 & 連絡先",
    expand: "展開",
    collapse: "折りたたむ",
    searchServices: "サービスを検索"
  },
  pt: {
    settings: "Configurações",
    theme: "Tema",
    language: "Idioma",
    system: "Sistema",
    light: "Claro",
    dark: "Escuro",
    favorites: "Favoritos",
    noFavorites: "Nenhum favorito adicionado",
    addToFavorites: "Adicionar aos favoritos",
    removeFromFavorites: "Remover dos favoritos",
    english: "Inglês",
    italian: "Italiano",
    spanish: "Espanhol",
    french: "Francês",
    german: "Alemão",
    chinese: "Chinês",
    japanese: "Japonês",
    portuguese: "Português",
    russian: "Russo",
    close: "Fechar",
    login: "Entrar",
    logout: "Sair",
    admin: "Administrador",
    search: "Buscar serviços...",
    serverStatus: "STATUS DO SERVIDOR",
    accountTitle: "Sua Conta",
    username: "Nome de usuário",
    email: "E-mail",
    role: "Função",
    registeredAt: "Registrado em",
    backToDashboard: "Voltar ao Painel",
    loggingOut: "Saindo...",
    heroDescription: "Monitore o status operacional de vários serviços e plataformas em tempo real. Fique informado sobre interrupções e problemas de desempenho.",
    loginDescription: "Digite suas credenciais para entrar",
    registerDescription: "Crie uma nova conta para acessar o painel",
    emailPlaceholder: "Digite seu e-mail",
    passwordPlaceholder: "Digite sua senha",
    usernamePlaceholder: "Escolha um nome de usuário",
    confirmPassword: "Confirmar Senha",
    confirmPasswordPlaceholder: "Confirme sua senha",
    passwordMismatch: "As senhas não coincidem",
    loggingIn: "Entrando...",
    creatingAccount: "Criando conta...",
    to: "até",
    toPresent: "até agora",
    unknown: "Desconhecido",
    categories: "Categorias",
    lastCheck: "Última verificação",
    games: "Jogos",
    streaming: "Streaming",
    bank: "Banco",
    social: "Social",
    mail: "Mail",
    shopping: "Compras",
    various: "Diversos",
    connection: "Conexão",
    browserai: "Navegador & IA",
    infoAndContacts: "Info & Contactos",
    expand: "Expandir",
    collapse: "Recolher",
    searchServices: "Buscar serviços"
  },
  ru: {
    settings: "Настройки",
    theme: "Тема",
    language: "Язык",
    system: "Система",
    light: "Светлая",
    dark: "Темная",
    favorites: "Избранное",
    noFavorites: "Нет добавленных в избранное",
    addFavorite: "Добавить в избранное",
    removeFavorite: "Удалить из избранного",
    english: "Английский",
    italian: "Итальянский",
    spanish: "Испанский",
    french: "Французский",
    german: "Немецкий",
    chinese: "Китайский",
    japanese: "Японский",
    portuguese: "Португальский",
    russian: "Русский",
    close: "Закрыть",
    login: "Войти",
    logout: "Выйти",
    admin: "Администратор",
    search: "Поиск сервисов...",
    serverStatus: "СТАТУС СЕРВЕРА",
    accountTitle: "Ваш аккаунт",
    username: "Имя пользователя",
    email: "Электронная почта",
    role: "Роль",
    registeredAt: "Зарегистрирован",
    backToDashboard: "Назад к панели",
    loggingOut: "Выход...",
    heroDescription: "Следите за состоянием различных сервисов и платформ в реальном времени. Будьте в курсе сбоев и проблем с производительностью.",
    loginDescription: "Введите свои данные для входа",
    registerDescription: "Создайте новый аккаунт для доступа к панели",
    emailPlaceholder: "Введите вашу почту",
    passwordPlaceholder: "Введите ваш пароль",
    usernamePlaceholder: "Выберите имя пользователя",
    confirmPassword: "Подтвердите пароль",
    confirmPasswordPlaceholder: "Подтвердите ваш пароль",
    passwordMismatch: "Пароли не совпадают",
    loggingIn: "Вход...",
    creatingAccount: "Создание аккаунта...",
    to: "до",
    toPresent: "по настоящее время",
    unknown: "Неизвестно",
    categories: "Категории",
    lastCheck: "Последняя проверка",
    games: "Игры",
    streaming: "Стриминг",
    bank: "Банк",
    social: "Социальные",
    mail: "Почта",
    shopping: "Покупки",
    various: "Разное",
    connection: "Связь",
    browserai: "Браузер и ИИ",
    infoAndContacts: "Информация и контакты",
    expand: "Развернуть",
    collapse: "Свернуть",
    searchServices: "Поиск сервисов"
  }
};

// Tipo per la traduzione che include la nuova chiave 'categories'
export type Translation = typeof translations.en & {
  categories: string;
};

interface SettingsContextType {
  theme: Theme;
  setTheme: (theme: Theme) => void;
  language: Language;
  setLanguage: (language: Language) => void;
  favorites: number[];
  addFavorite: (serviceId: number) => void;
  removeFavorite: (serviceId: number) => void;
  isFavorite: (serviceId: number) => boolean;
  t: Translation;
}

export const SettingsContext = createContext<SettingsContextType | null>(null);

export function SettingsProvider({ children }: { children: ReactNode }) {
  // Carica i valori salvati da localStorage o usa il tema chiaro di default
  const [theme, setThemeState] = useState<Theme>(() => {
    const savedTheme = localStorage.getItem("theme");
    return (savedTheme as Theme) || "light";
  });

  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem("language");
    return (savedLanguage as Language) || "en";
  });
  
  const [favorites, setFavorites] = useState<number[]>(() => {
    const savedFavorites = localStorage.getItem("favorites");
    return savedFavorites ? JSON.parse(savedFavorites) : [];
  });

  // Gestisce il cambiamento del tema
  useEffect(() => {
    localStorage.setItem("theme", theme);
    const root = window.document.documentElement;
    root.classList.remove("light", "dark");
    if (theme === "system") {
      const systemTheme = window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
      root.classList.add(systemTheme);
      const mediaQuery = window.matchMedia("(prefers-color-scheme: dark)");
      const handleChange = (e: MediaQueryListEvent) => {
        root.classList.remove("light", "dark");
        root.classList.add(e.matches ? "dark" : "light");
      };
      mediaQuery.addEventListener("change", handleChange);
      return () => mediaQuery.removeEventListener("change", handleChange);
    } else {
      root.classList.add(theme);
    }
  }, [theme]);

  // Gestisce il cambiamento della lingua
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  // Gestisce il cambiamento dei preferiti
  useEffect(() => {
    localStorage.setItem("favorites", JSON.stringify(favorites));
  }, [favorites]);

  // Funzioni per gestire l'impostazione del tema
  const setTheme = (newTheme: Theme) => {
    setThemeState(newTheme);
  };

  // Funzione per impostare la lingua
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
  };

  // Funzioni per gestire i servizi preferiti
  const addFavorite = (serviceId: number) => {
    if (!favorites.includes(serviceId)) {
      setFavorites([...favorites, serviceId]);
    }
  };

  const removeFavorite = (serviceId: number) => {
    setFavorites(favorites.filter(id => id !== serviceId));
  };

  const isFavorite = (serviceId: number): boolean => {
    return favorites.includes(serviceId);
  };

  // Ottiene le traduzioni correnti
  const t = translations[language];

  return (
    <SettingsContext.Provider
      value={{
        theme,
        setTheme,
        language,
        setLanguage,
        favorites,
        addFavorite,
        removeFavorite,
        isFavorite,
        t
      }}
    >
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error("useSettings must be used within a SettingsProvider");
  }
  return context;
}